version: '3'
services:
  bogo-it:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
    command: ["gunicorn", "-w", "1", "-b", "0.0.0.0:5000", "wsgi:app"]